[project]
name = "data-pipeline-semiconductor-industry"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kagglehub>=1.0.2",
]

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]

[tool.ruff.format]
quote-style = "double"

[dependency-groups]
dev = [
    "ruff>=0.16.5",
]
dbt = [
    "dbt-bigquery>=1.9,<1.10",
    "dbt-core>=1.9,<1.10",
]
